### ISSUE TITLE
Can we use Github to keep up with updates, etc?

### ISSUE THREAD

**Issue by bs** [earthspecies/spectral_hyperresolution#3]
Was looking at Basecamp for this, but perhaps best to keep this here.

**Comment by bs** [comment]
Seems like we can play with projects: https://github.com/earthspecies/spectral_hyperresolution/projects/1

**Comment by aza** [comment]
I’ve been trying a couple apps out that provide nice interfaces to Github issues. 

Githawk for iOS

Bee on the Mac.
